Feature/links
artlessnick/TaskManager pull request #11
Opened 2021-08-31 10:09 UTC by artlessnick

2021-09-01 17:34 UTC, greybutton requested changes
почему порт изменила?

2021-09-01 17:34 UTC, greybutton commented on app/views/layouts/application.html.slim
> +    = link_to "Sign up", new_developer_path, class: 'mdl-navigation__link'
поправь плис отступ, чтобы внутри nav.mdl-navigation было

2021-09-02 12:39 UTC, artlessnick commented
> почему порт изменила?

в задание написано "порт можно настроить...", я и настроила. в качестве практики, было полезно. вернуть?

2021-09-02 19:12 UTC, greybutton commented
да, давай вернем на стандартный 3000, если с ним все работает

2021-09-02 19:55 UTC, greybutton approved these changes

2021-09-02 20:46 UTC, merged