Feature/tasks
artlessnick/TaskManager pull request #16
Opened 2021-10-14 21:09 UTC by artlessnick

2021-10-18 19:38 UTC, greybutton requested changes

2021-10-18 19:38 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import TaskForm from '../../forms/TaskForm';
from 'forms/TaskForm';

2021-10-18 19:38 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import AddPopup from '../AddPopup/AddPopup';
from 'components/AddPopup';

2021-10-18 19:38 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup/EditPopup';
from 'components/EditPopup';

2021-10-18 19:38 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import EditPopup from '../EditPopup/EditPopup';
и лучше как нибудь группировать импорты. Пример

```
import Task from 'components/Task';
import ColumnHeader from 'components/ColumnHeader';
import AddPopup from 'components/AddPopup';
import EditPopup from 'components/EditPopup';
import TasksRepository from 'repositories/TasksRepository';
import TaskForm from 'forms/TaskForm';

import useStyles from './useStyles';
```

2021-10-18 19:38 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +  const MODES = {
MODES можно перенести рядом с initialBoard

2021-10-18 19:38 UTC, greybutton commented on app/javascript/packs/application.js
> +import TaskBoard from '../components/TaskBoard';
`from 'components/TaskBoard';` кажется должно работать

2021-10-18 19:38 UTC, greybutton commented on config/routes.rb
> +  namespace :api, defaults: {format: :json}  do
зачем дефолт? вроде в контроллере указан формат ответа app/controllers/api/application_controller.rb

2021-10-19 20:52 UTC, artlessnick commented on config/routes.rb
> +  namespace :api, defaults: {format: :json}  do
указан, но обрабатывается, как HTML и падает с 406 ошибкой, и я до сих пор разобраться не могу, что ни так, поэтому вот и дефолт)

2021-10-20 09:33 UTC, greybutton commented on config/routes.rb
> +  namespace :api, defaults: {format: :json}  do
как проверяешь? в тестах json приходит?

2021-10-20 14:28 UTC, artlessnick commented on config/routes.rb
> +  namespace :api, defaults: {format: :json}  do
тесты проходят. Терминал говорит "Processing by Api::V1::TasksController#index as HTML"

2021-10-21 17:18 UTC, greybutton approved these changes

2021-10-21 17:19 UTC, greybutton commented on config/routes.rb
> +  namespace :api, defaults: {format: :json}  do
хорошо, оставим так чтобы не застрять)

2021-10-22 10:31 UTC, merged