Feature/redux
artlessnick/TaskManager pull request #18
Opened 2021-10-28 16:08 UTC by artlessnick

2021-10-28 19:23 UTC, greybutton requested changes

2021-10-28 19:23 UTC, greybutton commented on app/javascript/MUITheme/MUITheme.js
> +import * as React from 'react';
если код не нужен, то удали комментарий, либо импортируй сразу useState

2021-10-28 19:23 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +      dispatch(moreLoadColumnSuccess({ ...data, columnId: state }));
loadColumnMoreSuccess

2021-10-28 19:23 UTC, greybutton commented on app/javascript/slices/TasksSlice.js
> +  const column = (state, page, perPage) =>
1 название функции - глагол
2 здесь можно и дублирование оставить

2021-10-28 19:23 UTC, greybutton commented on app/javascript/containers/TaskBoard.js
> +    setMode(MODES.EDIT);
это работает? здесь удалена строчка https://github.com/artlessnick/TaskManager/pull/18/files#diff-d8c700c1fec759300bf0e64b7db3e44a6b11b074f02befa3cece4207554abf36L40

2021-10-29 09:55 UTC, artlessnick commented on app/javascript/containers/TaskBoard.js
> +    setMode(MODES.EDIT);
оно работало)

2021-10-29 13:54 UTC, artlessnick commented on app/javascript/containers/TaskBoard.js
> +    setMode(MODES.EDIT);
прошу прощения, у меня еще вопрос по прошлому заданию https://github.com/artlessnick/TaskManager/pull/17 на сайте палец, а тут не эпрув) у меня так мержить рука не поднимается))

2021-10-29 20:38 UTC, greybutton commented on app/javascript/slices/useTasksActions.js
> +export default useTasksActions;
этот файл нигде не используется, зачем он?

2021-10-29 20:39 UTC, greybutton commented on app/javascript/containers/TaskBoard.js
> +    setMode(MODES.EDIT);
спасибо, что написала) Видимо кто то случайно нажал, оставил небольшой комментарий, в остальном все ок

2021-10-30 15:11 UTC, artlessnick commented on app/javascript/slices/useTasksActions.js
> +export default useTasksActions;
его здесь просто не должно было быть *facepalm*

2021-11-01 14:17 UTC, greybutton approved these changes

2021-11-01 19:06 UTC, merged